# Generated by Django 4.1.1 on 2023-05-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ang', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='adhar_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
